name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Step 3: Build, tag, and push image to Docker Hub
      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
  
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      # Step 3: Install dependencies
      - name: Install pip and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "flask==2.2.3" "werkzeug==2.2.3" pytest
          pip install -r requirements.txt  # Install dependencies from requirements.txt
      
      # Step 4: Run tests
      - name: Test with pytest
        run: |
          pytest test.py
