name: Python Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Flask app
      run: |
        nohup python app.py &
        sleep 5  # Wait for the app to start

    - name: Check if Flask app is running
      run: |
        curl --fail http://localhost:5000 || exit 1

    - name: Run tests with unittest
      run: |
        python test.py
