name: Python Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask app
      env:
        FLASK_APP: app.py
        FLASK_ENV: development
      run: |
        nohup flask run --host=0.0.0.0 --port=5000 &

    - name: Wait for Flask app to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5000/; then
            echo "App is ready!"
            break
          fi
          echo "Waiting for app..."
          sleep 2
        done

    - name: Run tests with unittest
      run: |
        python test.py
